# Generated by Django 5.0.9 on 2024-10-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('advance', 'Advance Access'), ('basic', 'Basic Access'), ('trial', 'Trial Access')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advance', 'basic', 'trial'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
