# Generated by Django 5.0.9 on 2024-10-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
