# Generated by Django 5.0.9 on 2024-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_price_created_at_price_featured_price_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['order', 'featured']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured'], 'permissions': [('advance', 'Advance Access'), ('basic', 'Basic Access'), ('trial', 'Trial Access')]},
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
