# Generated by Django 5.0.9 on 2024-10-13 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_price_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.price'),
        ),
    ]
