# Generated by Django 5.0.9 on 2024-10-13 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_usersubscription_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='mapped_id',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
    ]
