# Generated by Django 5.0.9 on 2024-10-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_usersubscription_mapped_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
