# Generated by Django 5.0.9 on 2024-10-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_price_end_price_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='end',
        ),
        migrations.RemoveField(
            model_name='price',
            name='start',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
