# Generated by Django 5.0.9 on 2024-10-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_remove_price_end_remove_price_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='first_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
