# Generated by Django 5.0.9 on 2024-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_usersubscription_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='cancelled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
