# Generated by Django 5.0.9 on 2024-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_alter_usersubscription_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
