# Generated by Django 5.0.9 on 2024-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_alter_usersubscription_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='to_remove',
            field=models.BooleanField(default=True),
        ),
    ]
