# Generated by Django 5.0.9 on 2024-10-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_subscription_to_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='to_remove',
        ),
    ]
